api/urls.py
from django.urls import path
from drf_spectacular.views import SpectacularSwaggerView, SpectacularAPIView
from rest_framework.authtoken.views import obtain_auth_token

app_name = 'api'

urlpatterns = [
    path('schema/', SpectacularAPIView.as_view(), name='schema'),
    path('docs/', SpectacularSwaggerView.as_view(url_name='api:schema'), name='docs'),
    path('api-token-auth/', obtain_auth_token)
]

iims/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('home/', TemplateView.as_view(template_name='iims/home.html')),
    path('league/', include('league.urls')),
    path('match/', include('match.urls')),
    path('react/', include('frontend.urls')),
    path('api/', include('api.urls')),
    path('officials/', include('officials.urls')),
    path('participant/', include('participant.urls')),
    path('team/', include('team.urls'))
]

league/urls.py
from django.urls import path, include
from rest_framework.routers import DefaultRouter

from .views import home, activity_view, empty_view, pool_view, week_view, day_view
from .api import GenderViewSet, TierViewSet, TermViewSet, LocationViewSet, \
    ActivityViewSet, DayViewSet, WeekViewSet, PoolViewSet

app_name = 'leagues'

router = DefaultRouter()
router.register('genders', GenderViewSet)
router.register('tiers', TierViewSet)
router.register('terms', TermViewSet)
router.register('locations', LocationViewSet)
router.register('activities', ActivityViewSet)
router.register('days', DayViewSet)
router.register('weeks', WeekViewSet)
router.register('pools', PoolViewSet)

api_urlpatterns = [

]

api_urlpatterns = api_urlpatterns + router.urls

urlpatterns = [
    path('home', home, name='home'),
    path('activity/<int:activity_id>', activity_view, name='activity'),
    path('pool/<int:pool_id>', pool_view, name='pool'),
    path('week/<int:week_id>', week_view, name='week'),
    path('day/<int:day_id>', day_view, name='day'),
    path('empy_view', empty_view, name='empty_view'),
    path('api/', include(api_urlpatterns), name='api'),
]

templates/iims/base.html
{% load static %}
{% load bootstrap5 %}

<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <title>UBC Recreation IIMS</title>

        <link rel="stylesheet" type="text/css" href="{% static 'iims/css/themed-bootstrap.css' %}">
        <link rel="stylesheet" type="text/css" href="{% static 'iims/css/common.css' %}">
        <script type="text/javascript" src="{% static 'iims/js/bootstrap.bundle.min.js' %}"></script>
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css">

        {% block head %}

        {% endblock %}

    </head>
    <body class="h-100 d-flex flex-column">
        <header>
            <nav class="navbar bg-primary p-3 justify-content-center">
            <div class="navbar-brand">
                <img class="bg-primary small-logo-img" src="{% static 'iims/images/ubc_rec_logo.png' %}" alt="ubc rec logo">
            </div>
            <div class="flex-fill text-center">
                <h1 class="text-white">Recreations Intramurals IIMS</h1>
            </div>
        </nav>
        </header>

        {% bootstrap_messages %}

        <div class="flex-grow-1">
            {% block body %}

            {% endblock %}
        </div>

        <footer>
            {% block footer %}

            {% endblock %}
        </footer>


    </body>
</html>

templates/iims/home.html
{% extends 'iims/base.html' %}

{% block body %}

<div class="d-flex justify-content-center p-3">
    <div>
        <p>Welcome to the Intramurals Information Management System (IIMS), made with love by JP Garcia.</p>

        <div class="d-flex flex-row justify-content-evenly">
            <div>
                <a href="{% url 'leagues:home' %}" class="btn btn-primary">Leagues</a>
            </div>

            <div class="text-center">
                <p>Coming Soon...</p>
                <a href="#" class="btn btn-primary">Events</a>
            </div>

            <div>
                <a href="{% url 'admin:index' %}" class="btn btn-secondary">Admin</a>
            </div>
        </div>

    </div>
</div>

{% endblock %}