api/urls.py
from django.urls import path
from drf_spectacular.views import SpectacularSwaggerView, SpectacularAPIView
from rest_framework.authtoken.views import obtain_auth_token

app_name = 'api'

urlpatterns = [
    path('schema/', SpectacularAPIView.as_view(), name='schema'),
    path('docs/', SpectacularSwaggerView.as_view(url_name='api:schema'), name='docs'),
    path('api-token-auth/', obtain_auth_token)
]

iims/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('home/', TemplateView.as_view(template_name='iims/home.html')),
    path('league/', include('league.urls')),
    path('match/', include('match.urls')),
    path('react/', include('frontend.urls')),
    path('api/', include('api.urls')),
    path('officials/', include('officials.urls')),
    path('participant/', include('participant.urls')),
    path('team/', include('team.urls'))
]

league/urls.py
from django.urls import path, include
from rest_framework.routers import DefaultRouter

from .views import home, activity_view, empty_view, pool_view, week_view, day_view
from .api import GenderViewSet, TierViewSet, TermViewSet, LocationViewSet, \
    ActivityViewSet, DayViewSet, WeekViewSet, PoolViewSet

app_name = 'leagues'

router = DefaultRouter()
router.register('genders', GenderViewSet)
router.register('tiers', TierViewSet)
router.register('terms', TermViewSet)
router.register('locations', LocationViewSet)
router.register('activities', ActivityViewSet)
router.register('days', DayViewSet)
router.register('weeks', WeekViewSet)
router.register('pools', PoolViewSet)

api_urlpatterns = [

]

api_urlpatterns = api_urlpatterns + router.urls

urlpatterns = [
    path('home', home, name='home'),
    path('activity/<int:activity_id>', activity_view, name='activity'),
    path('pool/<int:pool_id>', pool_view, name='pool'),
    path('week/<int:week_id>', week_view, name='week'),
    path('day/<int:day_id>', day_view, name='day'),
    path('empy_view', empty_view, name='empty_view'),
    path('api/', include(api_urlpatterns), name='api'),
]

league/models.py
import datetime

from django.db import models
from multiselectfield import MultiSelectField


class Gender(models.Model):
    """Represents a gender that can be used in Pools."""
    name = models.CharField(max_length=255)

    def __str__(self):
        return self.name


class Tier(models.Model):
    """Represents a tier that can be used in Pools."""
    name = models.CharField(max_length=255)

    def __str__(self):
        return self.name


class Term(models.Model):
    """Represents a term that can be used in Pools."""
    name = models.CharField(max_length=255)

    def __str__(self):
        return self.name


class Location(models.Model):
    """Represents a location where a game can be played."""
    name = models.CharField(
        max_length=255,
        help_text='Use an easy to read name of the location.'
    )

    def __str__(self):
        return self.name


class Activity(models.Model):
    """Represents an actual league activity"""
    name = models.CharField(
        max_length=255,
        help_text='The name of the activity, use a descriptive name users can understand!'
    )

    def __str__(self):
        return self.name


class Pool(models.Model):
    """Represents a pool for an activity."""
    DAY_CHOICES = (
        ('monday', 'Monday'),
        ('tuesday', 'Tuesday'),
        ('wednesday', 'Wednesday'),
        ('thursday', 'Thursday'),
        ('friday', 'Friday'),
        ('saturday', 'Saturday'),
        ('sunday', 'Sunday'),
    )

    name = models.CharField(
        max_length=255,
        help_text='The pool name, use something descriptive.'
    )
    game_duration = models.DurationField(
        help_text='The time duration of each game played in this pool.',
        default=datetime.timedelta(minutes=60)
    )
    days_of_play = MultiSelectField(
        choices=DAY_CHOICES,
        min_choices=1,
        help_text='What days is this pool playing?'
    )

    activity = models.ForeignKey(to=Activity, on_delete=models.CASCADE, related_name='pools')

    gender = models.ForeignKey(to=Gender, on_delete=models.CASCADE)
    tier = models.ForeignKey(to=Tier, on_delete=models.CASCADE)
    term = models.ForeignKey(to=Term, on_delete=models.CASCADE)
    locations_of_play = models.ManyToManyField(to=Location)

    def __str__(self):
        return '{} {}'.format(self.activity.name, self.name)


class Week(models.Model):
    """Represents a week of play where days can be filled with games."""
    start_date = models.DateField(
        help_text='The first day of the week.'
    )
    end_date = models.DateField(
        help_text='The last day of the week.'
    )

    pool = models.ForeignKey(to=Pool, on_delete=models.CASCADE, related_name='weeks')

    def __str__(self):
        return 'Week of {} to {}.'.format(self.start_date, self.end_date)


class Day(models.Model):
    """Represents a day of play within a week. The day can have any number of games scheduled."""
    week = models.ForeignKey(to=Week, on_delete=models.CASCADE, related_name='days')

    day = models.DateField()
    start_time = models.TimeField(help_text='Time when the first game can start!')
    end_time = models.TimeField(help_text='Last hour a game can be played this day. (Not the last start time)')
    location = models.ForeignKey(
        to=Location,
        help_text='Location where this day\'s games are to be played.',
        on_delete=models.CASCADE,
        related_name='days'
    )

    def __str__(self):
        return '{} at {}'.format(
            self.day.__str__(), self.location.__str__()
        )

league/views.py
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse, HttpResponseBadRequest
from django.shortcuts import render

from league.models import Activity, Pool, Week, Day


@login_required
def home(request):
    if request.method == 'GET':
        activities = Activity.objects.all()

        return render(request, 'league/league_home.html', context={
            'activities': activities
        })


@login_required
def activity_view(request, activity_id):
    if activity_id is None:
        return HttpResponseBadRequest('No activity ID given.')
    if request.method == 'GET':
        try:
            activity = Activity.objects.get(id=activity_id)
        except Activity.DoesNotExist:
            return HttpResponseBadRequest('Activity id given is not valid!')

        return render(request, 'league/activity_view.html', context={
            'activity': activity,
            'pools': activity.pools.all()
        })


@login_required
def pool_view(request, pool_id):
    if pool_id is None:
        return HttpResponseBadRequest('No pool id given!')
    if request.method == 'GET':
        try:
            pool = Pool.objects.get(id=pool_id)
        except Pool.DoesNotExist:
            return HttpResponseBadRequest('Pool id given is invalid!')

        locations = ''
        for location in pool.locations_of_play.all():
            locations += location.name + ', '

        return render(request, 'league/pool_view.html', context={
            'pool': pool,
            'weeks': pool.weeks.all(),
            'teams': pool.team_set.all(),
            'locations': locations,
            'days_of_play': pool.get_days_of_play_display()
        })


@login_required
def week_view(request, week_id):
    if week_id is None:
        return HttpResponseBadRequest('No week id given!')
    if request.method == 'GET':
        try:
            week = Week.objects.get(id=week_id)
        except Week.DoesNotExist:
            return HttpResponseBadRequest('Week id given is invalid!')

        days = week.days.all()

        return render(request, 'league/week_view.html', context={
            'week': week,
            'days_of_play': days,
        })


@login_required
def day_view(request, day_id):
    if day_id is None:
        return HttpResponseBadRequest('No day id given!')
    if request.method == 'GET':
        try:
            day = Day.objects.get(id=day_id)
        except Day.DoesNotExist:
            return HttpResponseBadRequest('Day id given is invalid!')

        matches = day.matches.all()

        return render(request, 'league/day_view.html', context={
            'day': day,
            'matches': matches
        })


@login_required
def empty_view(request):
    return HttpResponse('TODO')

league/templates/league/activity_view.html
{% extends 'iims/base.html' %}

{% block body %}
    <div class="container-fluid my-2 text-center">
        <h3>{{ activity }}</h3>
    </div>

    <div class="container-fluid my-2">
        <h4>Pools:</h4>
        {% for pool in pools %}
            <div class="d-flex flex-row justify-content-between align-items-center">
                <h6>{{ pool.name }}</h6>
                <p>{{ pool.gender.name }}</p>
                <p>{{ pool.tier.name }}</p>
                <p>{{ pool.term.name }}</p>
                <a href="{% url 'leagues:pool' pool.id %}" class="btn btn-outline-primary">Open</a>
            </div>
        {% empty %}
            <h5>There are no pools on this activity!</h5>
        {% endfor %}
    </div>

{% endblock %}

league/templates/league/day_view.html
{% extends 'iims/base.html' %}

{% block body %}
    <div class="container-fluid my-2 text-center">
        <h3>{{ day }}</h3>
    </div>

    <div class="container-fluid my-2">
        <h4>Matches:</h4>
        {% for match in matches %}
            <div>
                <a data-bs-toggle="collapse" href="#collapse{{ match.id }}"
                   role="button" aria-expanded="false" aria-controls="collapseExample">
                    <div class="d-flex flex-row justify-content-between align-items-center">
                        <h6>{{ match }}</h6>
                    </div>
                </a>
                <div class="collapse" id="collapse{{ match.id }}">
                    <div class="card card-body">
                        <div class="row">
                            <div class="col">
                                <h5>{{ match.home_team.team }}</h5>
                                <div class="col">
                                    {% for participant in match.home_team.team.team_roster.all %}
                                        <div class="d-flex flex-row justify-content-between">
                                            <h6>{{ participant }}</h6>
                                            <p>
                                                {% if participant.signed_waiver %} Waiver Signed
                                                {% else %} No Waiver
                                                {% endif %}
                                            </p>
                                        </div>
                                    {% endfor %}
                                </div>
                            </div>
                            <div class="col">
                                <h5>{{ match.away_team.team }}</h5>
                                <div class="col">
                                    {% for participant in match.away_team.team.team_roster.all %}
                                        <div class="d-flex flex-row justify-content-between">
                                            <h6>{{ participant }}</h6>
                                            <p>
                                                {% if participant.signed_waiver %} Waiver Signed
                                                {% else %} No Waiver
                                                {% endif %}
                                            </p>
                                        </div>
                                    {% endfor %}
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        {% empty %}
            <h5>There are no days of play on this activity!</h5>
        {% endfor %}
    </div>

{% endblock %}

league/templates/league/league_home.html
{% extends 'iims/base.html' %}

{% block body %}

    <div class="container-fluid my-4">
        <h3>Activities:</h3>
        <div class="container-fluid">
            {% for activity in activities %}
                <div class="d-flex flex-row justify-content-between align-items-center">
                    <h6>{{ activity.name }}</h6>
                    <div class="">
                        <a href="{% url 'leagues:activity' activity.id %}" class="btn btn-outline-primary">Open</a>
                    </div>
                </div>
            {% empty %}
                <h5>There are no activities!</h5>
            {% endfor %}
        </div>
    </div>

    <div class="d-flex flex-row flex-wrap justify-content-evenly p-3">
        <!-- gender button -->
        <a href="{% url 'leagues:empty_view' %}">
            <div class="card d-flex mx-1 my-2" style="min-width: 8rem">
                <div class="card-img-top text-center">
                    <i class="bi bi-gender-ambiguous" style="font-size: 3rem"></i>
                </div>
                <div class="card-body text-center">
                    <h4 class="card-title">Genders</h4>
                </div>
            </div>
        </a>
        <!-- tier button -->
        <a href="{% url 'leagues:empty_view' %}">
            <div class="card d-flex mx-1 my-2" style="min-width: 8rem">
                <div class="card-img-top text-center">
                    <i class="bi bi-list-ol" style="font-size: 3rem"></i>
                </div>
                <div class="card-body text-center">
                    <h4 class="card-title">Tiers</h4>
                </div>
            </div>
        </a>
        <!-- terms button -->
        <a href="{% url 'leagues:empty_view' %}">
            <div class="card d-flex mx-1 my-2" style="min-width: 8rem">
                <div class="card-img-top text-center">
                    <i class="bi bi-clock" style="font-size: 3rem"></i>
                </div>
                <div class="card-body text-center">
                    <h4 class="card-title">Terms</h4>
                </div>
            </div>
        </a>
        <!-- location button -->
        <a href="{% url 'leagues:empty_view' %}">
            <div class="card d-flex mx-1 my-2" style="min-width: 8rem">
                <div class="card-img-top text-center">
                    <i class="bi bi-pin-map" style="font-size: 3rem"></i>
                </div>
                <div class="card-body text-center">
                    <h4 class="card-title">Locations</h4>
                </div>
            </div>
        </a>
        <!-- unit button -->
        <a href="{% url 'leagues:empty_view' %}">
            <div class="card d-flex mx-1 my-2" style="min-width: 8rem">
                <div class="card-img-top text-center">
                    <i class="bi bi-house-door-fill" style="font-size: 3rem"></i>
                </div>
                <div class="card-body text-center">
                    <h4 class="card-title">Units</h4>
                </div>
            </div>
        </a>
        <!-- participant button -->
        <a href="{% url 'leagues:empty_view' %}">
            <div class="card d-flex mx-1 my-2" style="min-width: 8rem">
                <div class="card-img-top text-center">
                    <i class="bi bi-person" style="font-size: 3rem"></i>
                </div>
                <div class="card-body text-center">
                    <h4 class="card-title">Participants</h4>
                </div>
            </div>
        </a>
        <!-- officials button -->
        <a href="{% url 'leagues:empty_view' %}">
            <div class="card d-flex mx-1 my-2" style="min-width: 8rem">
                <div class="card-img-top text-center">
                    <i class="bi bi-file-ruled" style="font-size: 3rem"></i>
                </div>
                <div class="card-body text-center">
                    <h4 class="card-title">Officials</h4>
                </div>
            </div>
        </a>
        <!-- Info button -->
        <a href="{% url 'leagues:empty_view' %}">
            <div class="card d-flex mx-1 my-2" style="min-width: 8rem">
                <div class="card-img-top text-center">
                    <i class="bi bi-info-circle-fill" style="font-size: 3rem"></i>
                </div>
                <div class="card-body text-center">
                    <h4 class="card-title">Info</h4>
                </div>
            </div>
        </a>
    </div>

{% endblock %}

league/templates/league/pool_view.html
{% extends 'iims/base.html' %}

{% block body %}
    <div class="container-fluid my-2 text-center">
        <h3>{{ pool }}</h3>
        <div class="d-flex flex-row justify-content-evenly">
            <p>Gender: {{ pool.gender.name }}</p>
            <p>Term: {{ pool.term.name }}</p>
            <p>Tier: {{ pool.tier.name }}</p>
        </div>
    </div>

    <div class="row mx-2">
        <div class="col-7">
            <h4>Weeks:</h4>
            <div>
                {% for week in weeks %}
                    <div class="d-flex flex-row justify-content-between align-items-center mb-2">
                        <h6>{{ week }}</h6>
                        <a href="{% url 'leagues:week' week.id %}" class="btn btn-outline-primary">Open</a>
                    </div>
                {% empty %}
                    <h5>There are no weeks on this pool!</h5>
                {% endfor %}
            </div>
        </div>
        <div class="col d-flex flex-column justify-content-evenly align-content-center">
            <p>Location: {{ locations }}</p>
            <p>Days of Play: {{ days_of_play }}</p>
            <p>Game Duration: {{ pool.game_duration }}</p>
        </div>
    </div>

    <div class="container-fluid">
        <h4>Teams:</h4>
        <div>
            {% for team in teams %}
                <div class="d-flex flex-row justify-content-between align-items-center">
                    <h6>{{ team.name }}</h6>
                    <a href="#" class="btn btn-outline-primary">Open</a>
                </div>
            {% empty %}
                <h5>There are no teams on this pool!</h5>
            {% endfor %}
        </div>
    </div>

{% endblock %}

league/templates/league/week_view.html
{% extends 'iims/base.html' %}

{% block body %}

    <div class="container-fluid my-2 text-center">
        <h3>{{ week }}</h3>
    </div>

    <div class="container-fluid my-2">
        <h4>Days of play:</h4>
        {% for day in days_of_play %}
            <div class="d-flex flex-row justify-content-between align-items-center">
                <h6>{{ day }}</h6>
                <a href="{% url 'leagues:day' day.id %}" class="btn btn-outline-primary">Open</a>
            </div>
        {% empty %}
            <h5>There are no days of play on this activity!</h5>
        {% endfor %}
    </div>

{% endblock %}